= クラスタについて (ハイブリッド)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

クラスタは、アプリケーションの各インスタンスが互いに認識し、共通の情報を共有し、状況を同期する 1 つのデプロイメント対象として機能する一連のサーバです。オンプレミスクラスタでは、最大 8 個のサーバが高可用性処理単位に参加できるため、1 つのサーバが失敗した場合に別のサーバが、処理中のアプリケーションを引き継ぐことができます。1 つのクラスタは複数のアプリケーションを実行できます。

クラスタを作成する前に、クラスタの一部である各 Mule Runtime を作成する必要があります。同じバージョンの Mule Runtime をダウンロードしてインストールする必要があります。サポートされる、各コンポーネントのバージョンを以下に示します。

* Mule バージョン 3.7.0 以降
* Runtime Manager エージェントバージョン 1.1.1 以降

クラスタを作成する前に、Mule を Runtime Manager に接続する各サーバも作成する必要があります。

== マルチキャストクラスタとユニキャストクラスタの比較

Runtime Manager で、Runtime Manager コンソールにすでに登録されているサーバからクラスタを作成することができます。クラスタを構成するときに、クラスタ内のノードを識別するためのユニキャストオプションまたはマルチキャストオプションのいずれかを指定できます。

* *Unicast (ユニキャスト)*: ユニキャストクラスタでは、どのノードの IP アドレスを互いに関連付けるかを設定する必要があります。クラスタを構成するサーバ IP アドレスがどの IP アドレスかを示す以外に、特別なネットワーク設定は必要ありません。ユニキャストクラスタにサーバを追加する場合、各サーバの状況は [Running (実行中)] になっている必要があります。サーバに複数のインターフェースがある場合、ノードと他のノードとの直接通信を可能にする内部 IP を使用します。異なるサブネットにまたがるクラスタリングはサポートされません。
+
Mule はサーバを識別するための一意のハンドルとして IP アドレスを使用します。つまり、ユニキャストクラスタ上のサーバでは、DHCP を使用して IP アドレスを動的に割り当てることはできません。サーバが再起動され、DHCP を使用して新しい IP アドレスを取得した場合、サーバは新しい IP アドレスを使用してクラスタに再度参加する必要があります。

* *Multicast (マルチキャスト)*: マルチキャストクラスタは、互いに自動検出されたサーバをグループ化します。マルチキャストクラスタに含まれる各サーバは、同じネットワークセグメント上に存在する必要があります。
+
マルチキャストを使用する 1 つの利点は、クラスタ内のノードとして設定されたようにサーバを動作する必要がないことです。もう 1 つの利点は、クラスタを再起動することなくノードをクラスタに動的に追加できることです。
+
多くのネットワークでマルチキャスト機能がブロックされています。そのため、ネットワーク内でマルチキャストを許可するかどうかは、ネットワーク管理者に確認して判断してください。

== 関連情報

* xref:servers-create.adoc[Runtime Manager でのサーバの作成]
* xref:3.8@mule-runtime::mule-high-availability-ha-clusters.adoc[Mule 高可用性クラスタ]
