= ロードバランサについて (CloudHub)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

このトピックでは、CloudHub のロードバランサに関する一般的な情報を提供します。CloudHub は、インフラストラクチャコンポーネントを自動的にプロビジョニングするバックエンドの負荷分散サービスを提供します。

CloudHub は次の 2 種類のロードバランサを提供します。

* 共有ロードバランサ: 基本的な負荷分散機能を提供します。
* 専用ロードバランサ: これを使用すると、Anypoint Virtual Private Cloud (Anypoint VPC) 内で 1 つ以上のカスタムロードバランサをデプロイおよび設定できます。

== 共有ロードバランサ

CloudHub は、すべての環境で使用できるデフォルトの共有ロードバランサを提供します。共有ロードバランサは、TCP 負荷分散などの基本機能を提供します。共有ロードバランサでは、カスタム SSL 証明書やプロキシルールを設定できません。

また、共有ロードバランサでは、プラットフォームの安定性を確保できる低いレート制限が設定されます。MuleSoft はこの制限を定期的に監視し、必要に応じて拡大します。共有ロードバランサのレート制限はリージョンに従って適用されます。このため、アプリケーションを複数のリージョンのワーカーにデプロイしている場合、各リージョンのレート制限が異なる場合があります。

アプリケーションが共有ロードバランサのレート制限を超えると、ロードバランサは「503 Service Unavailable (503 サービスは使用できません)」の応答を返します。

カスタムロードバランサ設定を実行するか、レート制限のしきい値を上げるには、専用ロードバランサを使用する必要があります。

共有ロードバランサは TLS バージョン 1.1 および TLS 1.2 をサポートします。

== 専用ロードバランサ

専用ロードバランサを使用すると、次のことができます。

* アプリケーションを実行するさまざまな CloudHub ワーカー内で負荷分散を処理する。
* カスタム証明書を提供し、必要に応じて双方向 SSL クライアント認証を適用するように SSL 設定を定義する。
* カスタムドメインにアプリケーションをマップするプロキシルールを設定する。これにより、アプリケーションを 1 つのドメイン下でホストできます。

専用ロードバランサは Anypoint Platform の省略可能なコンポーネントです。環境で専用ロードバランサを使用するには、Anypoint VPC を実行している必要があります。同じ Anypoint VPC に複数の環境を関連付けることができます。これにより、同じ専用ロードバランサをさまざまな環境で使用できます。

Anypoint Platform 組織のロードバランサと Anypoint VPC エンドポイントは、API Portal から参照できます。

== 関連情報

* https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal]
* xref:cloudhub.adoc[CloudHub]
* xref:virtual-private-cloud.adoc[Virtual Private Cloud]
* xref:lb-architecture.adoc[ロードバランサのアーキテクチャについて]
