= サーバプロパティの表示 (ハイブリッド)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Manager では、Mule 環境のプロパティを表示および設定することができます。Runtime Manager には 2 種類のプロパティが表示されます。

== カスタムプロパティ

カスタムプロパティを使用して、Mule の JVM コンテナによって使用されるプロパティを定義できます。カスタムプロパティはキー/値ペアとして定義されます。

== 検出されたプロパティ

検出されたプロパティは、Mule のリモート環境によって定義されるプロパティです。これらには、Mule がインストールされているマシンの環境プロパティとシステムプロパティが含まれます。

表示できるプロパティの種別は次のとおりです。

* JVM 引数
* 環境プロパティ
* システムプロパティ

Runtime Manager では、リモートサーバの `System` Java クラスを照会する Runtime Manager エージェントからこれらのプロパティの値を取得します。リモートサーバプロパティの自動検出はデフォルトで無効になっています。この機能を使用するには、*[Enable Discovery (検出を有効化)]* をクリックする必要があります。この機能を有効にした後、Runtime Manager ではこれらのプロパティの暗号化されたものが内部データベースに保存されます。

この機能を完全に無効にするには、MuleSoft カスタマーサクセス担当者にお問い合わせください。

== サーバプロパティの表示

カスタムプロパティと検出されたプロパティを表示する手順は、次のとおりです。

. Anypoint Platform から *[Runtime Manager]* を選択します。
. *[Servers (サーバ)]* をクリックします。
. プロパティを表示するサーバを選択し、*[Manage Server (サーバを管理)]* をクリックします。
. *[Properties (プロパティ)]* タブをクリックします。
. *[Custom Properties (カスタムプロパティ)]* または *[Discovered Properties (検出されたプロパティ)]* をクリックします。
+
検出されたプロパティが表示されるようにするには、*[Enable Discovery (検出を有効化)]* をクリックする必要があります。この機能を有効にすると、これらのプロパティは暗号化された状態で Runtime Manager の内部データベースに保存されます。

*[Properties (プロパティ)]* タブから、プロパティを検索したり、キー、値、プロパティ種別で並べ替えたりすることもできます。

== 関連情報

* xref:servers-properties-create.adoc[カスタムサーバプロパティの作成]
