= VPC のプロビジョニングについて
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

組織での Anypoint VPC のプロビジョニングは、2 つの主要ステップで構成されます。

. VPC を作成する。 +
これはセルフサービスプロセスです。Runtime Manager UI または Anypoint Platform CLI を使用して VPC を作成できます。 +
[NOTE]
Anypoint Platform の基本サブスクリプションには 2 つの Anypoint VPC ライセンスが含まれており、Anypoint Platform 組織に 2 つの VPC の権利が与えられます。Anypoint VPC ライセンス制限に達すると、ユーザインターフェースの *[Create VPC (VPC を作成)]* オプションが無効になります。
. Anypoint VPC に接続する。 +
これは MuleSoft の担当者が行う必要があります。

[NOTE]
--
不要なダウンタイムを回避するために、新しい Anypoint VPC を最初に作成するときに Anypoint VPC 設定を定義することが重要です。 +
Anypoint VPC を作成した後にこれらの設定を編集する場合は、変更後にすべてのワーカーを削除し、再デプロイする必要があります。
--

これらの設定は次のとおりです。

* ネットワークのアドレス空間。 +
これで Anypoint VPC のサイズが判断されます。
* VPC の場所。 +
VPC でワーカーをホストできるようにするには、Anypoint VPC をビジネスグループまたは特定の CloudHub リージョンにバインドする必要があります。
+
** VPC の組織またはビジネスグループ。
** VPC の CloudHub リージョン。

以下の FAQ を参照し、適切な VPC セットアップを計画する方法を理解してください。

== FAQ: Anypoint VPC および VPN ライセンス要件の計算方法

IPSec VPN を介して Anypoint VPC を接続するには、デプロイメントシナリオに必要な数のライセンスを所有している必要があります。 

Anypoint Platform の基本サブスクリプションには 2 つの Anypoint VPC ライセンスが含まれており、Anypoint Platform 組織にライセンス供与された 2 つ VPC の権利が与えられます。Anypoint VPN ライセンスは Anypoint VPC ライセンスにバンドルされており、各 Anypoint VPC ライセンスでは、リモートロケーションにある 1 つのパブリック IP アドレスに接続する 1 つの VPN ゲートウェイの権利が組織に与えられます。 

[NOTE]
Anypoint VPN ライセンスは、Anypoint VPC ライセンスと 1 対 1 の関係にする必要はありません。たとえば、1 つの Anypoint VPC で 2 つの Anypoint VPN を使用し、もう 1 つの Anypoint VPC では VPN を使用しないことができます。  

Anypoint VPC からアクセスできるようにする各リモートロケーションに、Anypoint VPC ライセンスがもう 1 つ必要です。 


== FAQ: VPC のサイズの計算方法

Anypoint VPC を作成するときに、クラスレスドメイン間ルーティング (CIDR) 表記法を使用して、CIDR ブロック形式でネットワークの IP アドレス範囲を指定する必要があります。 +
このアドレス空間は Mule ワーカー用に予約されているので、VPC とピアリングする場合は、データセンターで使用されている他のアドレス空間と重複させることはできません。

Anypoint VPC の適切なサイズを計算するには、専用 IP アドレスの数は、デプロイしたワーカーの数とは同じでないことをまず理解する必要があります。 +
CloudHub にデプロイされた各ワーカーで、次の IP 割り当てが行われます。

* フォールトトレランスを向上するために、VPC サブネットを最大 4 つの可用性ゾーンに分割できます。
* いくつかの IP アドレスはインフラストラクチャ用に予約されています。
* ゼロダウンタイムを実現するためにワーカーごとに少なくとも 2 つの IP アドレス。

この構造により、Anypoint VPC に割り当てることができる最小のネットワークサブネットブロックは /24、最大は /16 になります。 +
/24 CIDR 表記のサブネットには、256 個の IP アドレスがあります。 +
ネットワーク用とブロードキャスト用に IP アドレスをそれぞれ 1 つ予約すると、ワーカーには 254 個のホストが残ります。これらは、それぞれ 62 個のホストを含む 4 つの可用性ゾーンに分割されます。ゼロダウンタイムを実現するために各ワーカーに 2 つの IP アドレスが必要になる可能性を考えると、ワーカーに割り当てられる残りの IP アドレスは約 30 個です。 +
また、VPC で必要な環境についても考慮します。  たとえば、Dev、QA、UAT でそれぞれ 300 個のインスタンスのスペースが必要な場合、最低でもインスタンス 1024 個分のサイズが必要です。

Anypoint VPC サブネットのサイズを決めるときの無難な経験則は、VPC にデプロイすることが予想される最大アプリケーション数の 10 倍を計算することです。

== FAQ: 組織内のどこに Anypoint VPC を配置するか

組織のシステム管理者として、Anypoint VPC を作成し、メイン組織内の任意のビジネスグループと共有することができます。 +
ただし、Anypoint VPC がビジネスグループによって継承されたら、そのビジネスグループのシステム管理者のみが Anypoint VPC を操作できます。たとえば、Anypoint 組織のシステム管理者またはビジネスグループ所有者は、Anypoint VPC を作成、または既存の (所有または継承した) Anypoint VPC を更新し、リージョン、環境、またはその両方のデフォルトに設定できます。 +
ただし、このような関連付けがすでに存在している場合、要求した Anypoint VPC によって上書きされます。

ビジネスグループの関連付けを指定しない場合、または組織にビジネスグループがない場合、Anypoint VPC の所有権はメイン組織に関連付けられたままになります。Anypoint VPC が作成される組織が VPC 所有者であり、この組織のシステム管理者が Anypoint VPC を共有できる唯一のユーザです。 +
Anypoint VPC は、メイン組織からビジネスグループのいずれか、またはビジネスグループから子ビジネスグループのいずれかに、縦に共有することができます。 +
ビジネスグループによって作成された Anypoint VPC を、階層内の上位にあるビジネスグループと共有することはできません。

マスタ組織で Anypoint VPC を作成し、他のビジネスグループと共有することをお勧めします。

== FAQ: Anypoint VPC を作成するときにどのリージョンを使用するか

使用可能な任意の CloudHub リージョン内に Anypoint VPC を作成できます。 +
推奨されるリージョンは、Anypoint VPC との接続方法によって異なります。VPN トンネルを使用する場合は、データセンターに最も近い CloudHub リージョンを選択します。 +
ただし、プライベート AWS VPC とピアリングする場合は、同じ AWS リージョンに Anypoint VPC を作成する必要があります。

== 関連情報

* xref:to-request-vpc-connectivity.adoc[ネットワークとの VPC 接続の要求方法]
