= Anypoint VPN 接続の作成
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Manager を使用して Anypoint VPN を作成します。 

== 前提条件

Anypoint VPN を作成する前に、Anypoint Virtual Private Cloud (Anypoint VPC) を作成する必要があります。詳細はxref:virtual-private-cloud.adoc[「Virtual Private Cloud」]を参照してください。 

[NOTE]
1 つの Anypoint VPC は最大 10 個の Anypoint VPN に対応できます。

Anypoint VPN を作成または設定するときには、次の情報を入力する必要があります。

* *Remote IP address (リモート IP アドレス):* VPN エンドポイントの公開 IP アドレス。
* *Remote and Local Autonomous System Number (ASN) (リモートおよびローカルの自律システム番号 (ASN))*: ルーティングのプレフィックスのコレクションを指定します。Anypoint VPN を作成する前に、リモート ASN とローカル ASN の両方を設定する必要があります。これは動的ルーティングを使用する場合のみ必須です。
* *Classless Inter-Domain Routing (CIDR) (クラスレスドメイン間ルーティング (CIDR))*: ネットワークのルーティングアドレスを指定します。これは静的ルーティングを使用する場合のみ必須です。
* *Pre-shared Key (PSK) (事前共有キー (PSK)):* Anypoint Platform とネットワークを接続するネットワークトンネルによって使用される共有シークレット。この値は *[Automatic Tunnel Configuration (自動トンネル設定)]* を選択すると自動生成されます。
* *Point-to-Point CIDR (ポイントツーポイント CIDR):* ネットワークトンネルによって使用される IP 範囲。トンネルごとに一意の IP アドレス範囲を設定する必要があります。この値は *[Automatic Tunnel Configuration (自動トンネル設定)]* を選択すると自動生成されます。


== Anypoint VPNの作成

. Anypoint Platform にサインインして、*[Runtime Manager]* を選択します。
. Anypoint VPN を作成する環境を選択します。
. 左側のメニューで *[VPNs (VPN)]* をクリックしてから *[Create VPN (VPN を作成)] *をクリックします。
. Anypoint VPN について次の情報を入力または選択します。 +
* *Name (名前)* - Anypoint VPN の名前を入力します。 
* *VPC* - ドロップダウンリストから、Anypoint VPN 接続の Virtual Private Cloud を選択します。
* *Remote IP address (リモート IP アドレス)* - VPN エンドポイントの公開 IP アドレスを入力します。
. 使用するルーティング種別を選択します。 
+
[NOTE]
*[BGP]* か *[Static (静的)]* を選択できます。デバイスでサポートされている場合は、ボーダーゲートウェイプロトコル (BGP) 種別を選択してください。
+
[%header%autowidth.spread]
|===
|動的ルーティングを作成する場合 |静的ルーティングを作成する場合
a| *[BGP]* を選択して、次の値を入力します。

* *Remote ASN (リモート ASN)* - バックエンドに対応する ASN を入力します。 +
デフォルト値は `65001` です。
* *Local ASN (ローカル ASN)* - MuleSoft 側の ASN を割り当てます。 +
デフォルト値は `64512` です。

a| *[Static (静的)]* を選択してから: 

. *[CIDR]* 項目に、VPN 経由でアクセスする必要のあるサブネットを入力します。 +
例: `10.0.0.0/8`
. (省略可能) サブネットを追加するには、*[Add New Rule (新規ルールを追加)]* をクリックして、上のステップを繰り返します。
|===
. ​*[Tunnel Configuration (トンネル設定)]*​種別を選択します。 +
​*[Automatic (自動)]*​ または *[Custom (カスタム)]* を選択できます。ほとんどの場合は *[Automatic (自動)]* で十分です。以下のステップは、選択したトンネル種別によって異なります。 
+
[%header%autowidth.spread]
|===
|​*[Automatic (自動)]*​ トンネル設定を使用する場合 |​*[Custom (カスタム)]*​ トンネル設定を使用する場合
a|​*[Automatic (自動)]* を選択します。 +
他の入力は不要です。このオプションは、Anypoint VPN に必要なトンネルを自動的に設定します。

a|.*[Custom (カスタム)]* を選択して、両方のトンネルの値を入力します。
. *[PSK]* 項目に、先頭が 0 ではない 8 ～ 64 文字の値を入力します。 + 
英数字、ピリオド (.)、およびアンダースコア (&#95;) のみを使用してください。 
. *[Point-to-Point CIDR (ポイントツーポイント CIDR)]* 項目に、VPN トンネルの内部アドレスの IP アドレス範囲を入力します。 +
`169.254.0.0/16` 範囲から、サイズ /30 の CIDR ブロックを指定できます。CIDR ブロックはすべての VPN 接続で一意であることが必要です。 +
次の CIDR ブロックは使用できません。

----
169.254.0.0/30
169.254.1.0/30
169.254.2.0/30
169.254.3.0/30
169.254.4.0/30
169.254.5.0/30
169.254.169.252/30
----
|===
. *[Create VPN (VPN を作成)]* をクリックします。
+
[NOTE]
Anypoint VPN 接続を作成した後にトンネル設定を変更することはできません。既存の接続の設定を変更するには、Anypoint VPN 接続を削除して新しい接続を作成する必要があります。
. ​*[Download (ダウンロード)]*​をクリックして、VPN エンドポイントの設定ファイルをダウンロードします。 
+
[NOTE]
提供されている設定ファイルは、サポートされる最小限の IPsec 設定を使用した設定例です。Anypoint VPN でサポートされている IPsec 設定の組み合わせを使用して、自分の要件に合わせて設定を調整してください。
. VPN エンドポイントを設定します。 +
選択した設定オプションによっては、追加の設定ステップが必要になる場合があります。エンドポイントの設定については、使用している VPN エンドポイントのドキュメントを参照し、ネットワークのコンポーネントを正しく設定してください。  

[NOTE]
予期しない動作を回避するためには、VPN エンドポイントで両方のトンネルを設定する必要があります。 

== VPN とトンネルの状況

作成した新しい VPN 接続が VPN のリストに表示されます。インフラストラクチャの作成中は、*[Status (状況)]* 列には *[PENDING (待機中)]*、両方の Anypoint VPN トンネルには *[DOWN (停止中)]* と最初に表示されます。 

[NOTE]
設定によっては、正常な動作中にもトンネルに *[DOWN (停止中)]* と表示される場合があります。

[%header%autowidth.spread]
|===
|状況 |トンネル 1/トンネル 2 |説明
|`Pending` |`DOWN\DOWN` |VPN 接続が作成されたばかりで、アクションはバックグラウンドで待機中です。VPN のを作成してから 10 ～ 15 分は、この状況が表示されることがあります。
|`Available` |`DOWN\DOWN` |VPN 接続が作成されていますが、リモート側が設定されていないか、またはトラフィックを送信していません。
|`Available` |`Up\Up` または `Up\Down` |VPN 接続が作成され、リモート側が接続を正常に確立しました。VPN とルーティングの種別により、トンネルはアクティブ/アクティブモードまたはアクティブ/パッシブモードで動作します。
|`Failed` |`DOWN\DOWN` | VPN 接続が正常に作成されませんでした。VPN を削除してやり直す必要があります。この障害が再発する場合は、MuleSoft サポートにお問い合わせください。
|===

=== 関連情報

* xref:vpn-about.adoc[Anypoint VPN]
* xref:virtual-private-cloud.adoc[Anypoint Virtual Private Cloud]
* https://support.mulesoft.com/s/article/Anypoint-VPN-Knowledge-Articles[Anypoint VPN ナレッジ記事]
